### ISSUE TITLE
Is there any ways I can export Arabica character, or how can I change the Encoding

### ISSUE THREAD

**Issue by SalarPro** [billthecoder046/to_csv#1]
Some of my users type their name using Arabica character, the output is ex: [Ø¹Ø¨Ø¯Ø§Ù„Ù„Ù‡ Ù…Ø­Ù…Ø¯]

**Comment by billthecoder046** [comment]
For now, there is no way to perform Arabic Character export. Will consider this in the future!

**Comment by billthecoder046** [comment]
Closing the issue because of no more activity.
