### ISSUE TITLE
Custom name export file from within app

### ISSUE THREAD

**Issue by TrueKing** [billthecoder046/to_csv#10]
Hello. I have used this package about two or so times in my projects and I am really grateful to have had this solution to my need. Much appreciated.

- I have a suggestion to give the user of an app the opportunity to name the export file (like with a textController or record id from DB) even before leaving their app to specify save directory so that so that the second view can be sort of a preview.

- Also I think the timestamp can be likewise implemented to indicate time of perhaps a saved record rather than export date.

I should've done this before making any move but no-thanks to my ignorance, I did the otherwise. Kindly review this suggestion against overall benefit.

**Comment by billthecoder046** [comment]
Thanks for suggestions and appreciations. I will look into it....

**Comment by TrueKing** [comment]
Awesome, thank you!

**Comment by billthecoder046** [comment]
This issue is resolved. Thanks to @TrueKing
