### ISSUE TITLE
intl 0.19

### ISSUE THREAD

**Issue by pom11** [billthecoder046/to_csv#15]
*Because no versions of to_csv match >2.2.1 <3.0.0 and to_csv 2.2.1 depends on intl ^0.18.0, to_csv ^2.2.1 requires intl ^0.18.0.*

request to bump to intl ^0.19.0 
Flutter SDK on 3.16.x depends on intl 0.19.0

**Comment by ryanmcfall** [comment]
I would also appreciate it if intl could be bumped to ^0.19.0.

**Comment by billthecoder046** [comment]
This is issue is resolved in to_csv 3.0.0 version. Thanks!
