### ISSUE TITLE
flutter_lints 4.0.0

### ISSUE THREAD

**Issue by N1kolaus** [billthecoder046/to_csv#17]
_Because to_csv 3.0.1 depends on flutter_lints ^2.0.0 and no version of to_csv match >3.0.1 <4.0.0, to_csv ^3.0.1 requires flutter_lints ^2.0.0_

Request bump to flutter_lints ^4.0.0

Thank you for your time and your awesome work!

**Comment by billthecoder046** [comment]
Sure I'll update it soon!

**Comment by billthecoder046** [comment]
Resolved in to_csv: ^3.0.3
