### ISSUE TITLE
File not saved

### ISSUE THREAD

**Issue by LydianJay** [billthecoder046/to_csv#20]
Flutter Version: 3.24.1
Dart: 3.5.1
DevTools: 2.37.2
Platform: Windows 10 
OS Build: 19041.1

File dialog opens up fine but after clicking save I cant find the file that supposedly there
I tried adding ".csv" and still no file saved
There was no thrown error and the return value is null

code below

`void _toCSV() async {
    final List<List<String>> val = [];

    for (final v in attendance) {
      val.add(v.toListString());
    }

    final res = await exportCSV
        .myCSV(AttendanceModel.getHeaderTitle(), val)
        .onError((E, stack) {
      debugPrint(stack.toString());
    });
    debugPrint('Result: ${res.toString()}');
  }
  ` 

![image](https://github.com/user-attachments/assets/8a670b4a-43fd-4c68-96db-56567f70ed4c)

**Comment by marconetsf** [comment]
Same thing here, it prints  '***** Gonna Create csv' but nothing happens.

**Comment by marconetsf** [comment]
Actually it appears at quick access (windows) at recent files, but when I try to open, it just seems it was deleted or moved.

**Comment by LydianJay** [comment]
I stopped using this library and encoded the csv my self
 ```
class AttendanceModel {
  final int rfid;

final int day;
  final int month;
  final int year;
  final int hour;
  final int min;
  final int type;

  AttendanceModel({
    required this.rfid,
    required this.day,
    required this.month,
    required this.year,
    required this.hour,
    required this.min,
    required this.type,
  });

  List<String> toListString() {
    return [
      rfid.toRadixString(16),
      day.toString(),
      month.toString(),
      year.toString(),
      hour.toString(),
      min.toString(),
      type == 1 ? 'Time In' : 'Time Out',
    ];
  }

  static String getHeaderTitleAsString() {
    return "RFID,Day,Month,Year,Hour,Minutes,Type";
  }

  String toCSV() {
    return "${rfid.toRadixString(16).toUpperCase()},${day.toString()},${month.toString()},${year.toString()},${hour.toString()},${min.toString()},${type == 1 ? 'Time In' : 'Time Out'}";
  }

  static List<String> getHeaderTitle() {
    return [
      'RFID',
      'Day',
      'Month',
      'Year',
      'Hour',
      'Minutes',
      'Type',
    ];
  }
}
```

**Comment by billthecoder046** [comment]
Yeah this package is not well tested for Windows Platform @LydianJay.

**Comment by LydianJay** [comment]
why close?
