### ISSUE TITLE
Headers are not being exported

### ISSUE THREAD

**Issue by squeezeoj** [billthecoder046/to_csv#3]
I love the simplicity of this.

However, when I use your basic example, my output file does not contain the headers.  Here's what I get:

```
1,Bilal Saeed,1374934,912839812
2,Ahmar,21341234,192834821
```

These lines do not seem to be working:

> header.add('No.');
> header.add('User Name');
> header.add('Mobile');
> header.add('ID Number');

Am I missing something?  

How can I get the headers to print in the export file?

THANKS!

**Comment by squeezeoj** [comment]
My work-around is to manually add the header list as the first list of lists.

**Comment by GraSim** [comment]
Same here, the headers are not being exported.

I will use @squeezeoj workaround for now

**Comment by davidecolussi** [comment]
I fixed and created a pull request

**Comment by billthecoder046** [comment]
Issue is resolved. Thanks to @davidecolussi
