### ISSUE TITLE
The argument type 'String?'

### ISSUE THREAD

**Issue by berkayhh** [billthecoder046/to_csv#5]
: Error: The argument type 'String?' can't be assigned to the parameter type 'Object' because 'String?' is nullable and 'Object' isn't.
element_subclasses.dart:2752
 - 'Object' is from 'dart:core'.
    final parsed = css.parse(text);

**Comment by billthecoder046** [comment]
Can you please explain a bit i.e when does this error occur?

**Comment by billthecoder046** [comment]
Issue was resolved in new version 2.0.7.
