### ISSUE TITLE
file_server Error

### ISSUE THREAD

**Issue by mhnadimy** [billthecoder046/to_csv#6]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method saveAs on channel file_saver)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      PlatformHandlerAll.saveAs (package:file_saver/src/platform_handler/platform_handler_all.dart:69:14)
<asynchronous suspension>
#2      Saver.saveAs (package:file_saver/src/saver.dart:13:12)
<asynchronous suspension>
#3      FileSaver.saveAs (package:file_saver/file_saver.dart:128:20)
<asynchronous suspension>
#4      myCSV (package:to_csv/to_csv.dart:69:5)
<asynchronous suspension>

**Comment by bilalsaeedjh** [comment]
Is your file saver package up to date? Moreover please explain the error a bit i.e when does this occure?

**Comment by billthecoder046** [comment]
You are using emulator I belive. Please use physical device (iOS or Android only).
