### ISSUE TITLE
Download/share option

### ISSUE THREAD

**Issue by xxJeevesxx** [billthecoder046/to_csv#7]
Hi, thanks for this, simple, clean and easy. I'm wondering if there is an easy way to integrate some options for sharing the csv file directly from the app instead of only saving to the local files. 

Thanks!

**Comment by billthecoder046** [comment]
Hi there! Sharing to what platforms?

**Comment by xxJeevesxx** [comment]
Like if I wanted to text or email the CSV? Or message in telegram or some other messaging platform.

**Comment by billthecoder046** [comment]
Will look into this in next version.

**Comment by xxJeevesxx** [comment]
Very cool. Excited to see the changes!. Do you have an eta for publishing changes to pub.dev? Or should I add the package directly from GitHub?

**Comment by billthecoder046** [comment]
Yes i do have. Once the changes are made, i will upload the new version and
you could download it from pub.dev.

**Comment by billthecoder046** [comment]
New version 2.0.7 contains the sharing functionality of downloaded csv file on android and iOS physical devices.

**Comment by xxJeevesxx** [comment]
Awesome, thank you! I'll check it out.
